customer:
  property: Bootcoin Profile Local
api:
  customer:
    baseUri: http://customer/customer
    personUri: http://customer/person
    companyUri: http://customer/company
    employeeUri: http://customer/employee
    signerUri: http://customer/signer
    holderUri: http://customer/holder
  product:
    baseUri: http://product/product
    savingsAccountUri: http://product/savings-account
    checkingAccountUri: http://product/checking-account
    fixedTermUri: http://product/fixed-term
    cardUri: http://product/card
    loanUri: http://product/loan
  movement:
    baseUri: http://movement/movement
server:
  port: 8096
kafka:
  bootstrapAddress: http://localhost:29092
  group-id: bootcamp19
cache:
  enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
  instance:
    instanceId: ${random.uuid}
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bootcamp_19
  redis:
    host: localhost
    port: 6379