customer:
  property: Customer Profile Dev
server:
  port: 8083
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bootcamp_19
logging:
  config: classpath:logback.xml