customer:
  property: Customer Profile Dev
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
  instance:
    instanceId: ${random.uuid}
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bootcamp_19
logging:
  config: classpath:logback.xml