customer:
  property: Gateway Profile Dev
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
  instance:
    instanceId: ${random.uuid}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path: /customer/**
logging:
  config: classpath:logback.xml