customer:
  property: Gateway Profile Dev
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8082/eureka/
  instance:
    instanceId: ${random.uuid}
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/customer/**,/employee/**,/holder/**,/person/**,/signer/**,/company/**
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/card/**,/checking-account/**,/fixed-term/**,/loan/**,/product/**,/savings-account/**
        - id: movement
          uri: lb://MOVEMENT
          predicates:
            - Path=/employees/**,/products/**,/movement/**
logging:
  config: classpath:logback.xml