customer:
  property: Gateway Profile Dev
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://172.26.0.6:8082/eureka/
  instance:
    instanceId: ${random.uuid}
    preferIpAddress: true
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/customer/**,/employee/**,/holder/**,/person/**,/signer/**,/company/**
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/card/**,/checking-account/**,/fixed-term/**,/loan/**,/product/**,/savings-account/**
        - id: movement
          uri: lb://MOVEMENT
          predicates:
            - Path=/employees/**,/products/**,/movement/**
        - id: h2_console
          uri: ${rewrite.backend.uri:http://172.26.0.8:9001}
          predicates:
            - Path=/h2-console/**
        - id: h2_console2
          uri: ${rewrite.backend.uri:http://172.26.0.8:9001/actuator}
          predicates:
            - Path=/h2console/**
logging:
  config: classpath:logback.xml