customer:
  property: Movement Profile Dev
api:
  customer:
    baseUri: http://localhost:8083/customer
    personUri: http://localhost:8083/person
    companyUri: http://localhost:8083/company
  product:
    baseUri: http://localhost:8082/product
    savingsAccountUri: http://localhost:8082/savings-account
    checkingAccountUri: http://localhost:8082/checking-account
    fixedTermUri: http://localhost:8082/fixed-term
    cardUri: http://localhost:8082/card
    loanUri: http://localhost:8082/loan
server:
  port: 8084
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bootcamp_19
logging:
  config: classpath:logback.xml