customer:
  property: Movement Profile Dev
api:
  customer:
    baseUri: http://localhost:8083/customer
    personUri: http://localhost:8083/person
    companyUri: http://localhost:8083/company
    employeeUri: http://localhost:8083/employee
    signerUri: http://localhost:8083/signer
    holderUri: http://localhost:8083/holder
  product:
    baseUri: http://localhost:8083/product
    savingsAccountUri: http://localhost:8083/savings-account
    checkingAccountUri: http://localhost:8083/checking-account
    fixedTermUri: http://localhost:8083/fixed-term
    cardUri: http://localhost:8083/card
    loanUri: http://localhost:8083/loan
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
  instance:
    instanceId: ${random.uuid}
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bootcamp_19
resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      example:
        base-config: shared
  timelimiter:
    configs:
      shared:
        timeout-duration: 2s
        cancel-running-future: true
    instances:
      example:
        base-config: shared
logging:
  config: classpath:logback.xml