customer:
  property: Movement Profile Dev
api:
  customer:
    baseUri: http://localhost:8083/customer
    personUri: http://localhost:8083/person
    companyUri: http://localhost:8083/company
    employeeUri: http://localhost:8083/employee
    signerUri: http://localhost:8083/signer
    holderUri: http://localhost:8083/holder
  product:
    baseUri: http://localhost:8083/product
    savingsAccountUri: http://localhost:8083/savings-account
    checkingAccountUri: http://localhost:8083/checking-account
    fixedTermUri: http://localhost:8083/fixed-term
    cardUri: http://localhost:8083/card
    loanUri: http://localhost:8083/loan
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
  instance:
    instanceId: ${random.uuid}
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bootcamp_19
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
logging:
  config: classpath:logback.xml