product:
  property: Product Profile Dev
server:
  port: 8091
kafka:
  bootstrapAddress: 172.26.0.4:29092
eureka:
  client:
    service-url:
      defaultZone: http://172.26.0.6:8082/eureka/
  instance:
    instanceId: ${random.uuid}
    preferIpAddress: true
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
spring:
  data:
    mongodb:
      host: 172.26.0.10
      port: 27018
      database: bootcamp_19
logging:
  config: classpath:logback.xml