product:
  property: Product Profile Dev
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.3:8082/eureka/
  instance:
    instanceId: ${random.uuid}
    hostname: host.docker.internal
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: bootcamp_19
logging:
  config: classpath:logback.xml