product:
  property: Product Profile Dev
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8082/eureka/
  instance:
    instanceId: ${random.uuid}
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: bootcamp_19
logging:
  config: classpath:logback.xml