customer:
  property: Reporting Service Profile Dev
server:
  port: 8083
kafka:
  bootstrapAddress: 172.26.0.4:9092
  group-id: bootcamp19
eureka:
  client:
    service-url:
      defaultZone: http://172.26.0.6:8082/eureka/
  instance:
    instanceId: ${random.uuid}
    preferIpAddress: true
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - h2console
  endpoint:
    health:
      show-details: always
spring:
  r2dbc:
    h2:
      url: file:/tmp/bootcamp19;DB_CLOSE_DELAY=-1;
  h2:
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
    console:
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
      port: 8085
      webAllowOthers: true
      web-allow-others: true
      settings:
        trace: false
        webAllowOthers: true
        web-allow-others: true
logging:
  config: classpath:logback.xml