customer:
  property: Reporting Service Profile Dev
server:
  port: 8083
kafka:
  bootstrapAddress: http://172.17.0.10:9092
  group-id: bootcamp19
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.3:8082/eureka/
  instance:
    instanceId: ${random.uuid}
    preferIpAddress: true
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
spring:
  r2dbc:
    h2:
      url: file:/var/www/h2/bootcamp19;DB_CLOSE_DELAY=-1;
  h2:
    console:
      enabled: true
      port: 9001
logging:
  config: classpath:logback.xml