# This is a basic workflow to help you get started with Actions

name: Redeploy Discovery Server
on:
  push:
    paths:
      - 'discovery-server-dev.yml'
  pull_request:
    paths:
      - 'discovery-server-dev.yml'
jobs:
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_DISCOVERY_SERVER_WEBHOOK_URL  }}